# 数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/car_online_manage?serverTimezone=GMT%2B8&characterEncoding=utf8&characterSetResults=utf8
    username: root
    password: fuck3148481
# 日志配置（开发用）
logging:
  level:
    com:
      longder: DEBUG
# 服务端口
server:
  port: 5188
